### ISSUE TITLE
Not working any longer... MM is black

### ISSUE THREAD

**Issue by OberfragGER** [BenRoe/MMM-SystemStats#47]
Hi,
i updated my MM to the actual version and did also apt-get update && apt-get upgrade.
Very sad that this is not maintained any longer... i liked it.

WIth the MM-SystemStats the whole mirror is not loading any longer. Is there a possibilty to fix that?

`/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-SystemS                                                                                                                                                             tats/node_helper.js:13:15)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.j                                                                                                                                                             s:1108:10) {
0|mm       |   code: 'MODULE_NOT_FOUND',
0|mm       |   requireStack: [
0|mm       |     '/home/pi/MagicMirror/modules/MMM-SystemStats/node_helper.js',
0|mm       |     '/home/pi/MagicMirror/js/app.js',
0|mm       |     '/home/pi/MagicMirror/js/electron.js',
0|mm       |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/defa                                                                                                                                                             ult_app.asar/main.js',
0|mm       |     undefined
0|mm       |   ]
0|mm       | }
0|mm       | [04.10.2021 13:13.47.982] [ERROR] MagicMirror will not quit, but it                                                                                                                                                              might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [04.10.2021 13:13.47.982] [ERROR] If you think this really is an is                                                                                                                                                             sue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/iss                                                                                                                                                             ues
`

I also tried to reninstall:
`pi@MagicMirror:~/MagicMirror/modules $ git clone https://github.com/BenRoe/MMM-SystemStats
Klone nach 'MMM-SystemStats' ...
remote: Enumerating objects: 234, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 234 (delta 0), reused 1 (delta 0), pack-reused 231
Empfange Objekte: 100% (234/234), 88.04 KiB | 370.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (125/125), Fertig.
pi@MagicMirror:~/MagicMirror/modules $ cd MMM-SystemStats/ && npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
added 1 package from 1 contributor and audited 1 package in 1.104s
found 0 vulnerabilities

pi@MagicMirror:~/MagicMirror/modules/MMM-SystemStats $ git pull
Bereits aktuell.
`

My config:
`    {
      module: 'MMM-SystemStats',
      position: 'bottom_right',
      config: {
        updateInterval: 60000,
        view: 'textAndIcon'
      }
    },`

Any Ideas?

**Comment by OberfragGER** [comment]
Solution:
https://forum.magicmirror.builders/topic/15664/updated-to-2-17-but-mm-not-launching/9


@oberfragger it says module not found
we deleted a bunch of older libraries because one was discontinued (deprecated) due to a security problem not going to be fixed
many mm modules used them but didn’t document the usage. oops
I don’t see the name of the library
but looking at the node_helper.js shows

require('request')
which is the trouble lib

u can add it back for this module , do

```
npm init -y
npm install request -- save
``|
```
